export const products = [
  {
    id: 1,
    title: "Counter-Strike: Global Offensive",
    price: 610,
    stock: 2,
    description: "Juego de acción por equipos",
    category: "Shooter",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg?t=1683566799",
  },
  {
    id: 2,
    title: "Street Fighter™ 6",
    price: 2400,
    stock: 5,
    description: "¡Aquí llega el peso pesado de Capcom!",
    category: "Lucha",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1364780/header.jpg?t=1685680525",
  },
  {
    id: 3,
    title: "Call of Duty®: Modern Warfare® II",
    price: 1649,
    stock: 6,
    description: "Los jugadores se verán inmersos en un conflicto",
    category: "Shooter",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1938090/header_alt_assets_3_spanish.jpg?t=1686100464",
  },
  {
    id: 4,
    title: "Rust",
    price: 849,
    stock: 5,
    description: "El único objetivo en Rust es sobrevivir.",
    category: "Shooter",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg?t=1678981332",
  },
  {
    id: 5,
    title: "Mortal Kombat 1",
    price: 2199,
    stock: 12,
    description:
      "Descubre un nuevo universo de Mortal Kombat creado por Liu Kang",
    category: "Lucha",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1971870/header.jpg?t=1685036642",
  },
  {
    id: 6,
    title: "DRAGON BALL FighterZ",
    price: 1199,
    stock: 12,
    description:
      "luchas espectaculares e interminables con luchadores superpoderosos.",
    category: "Lucha",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/678950/header.jpg?t=1677091503",
  },
  {
    id: 7,
    title: "DayZ",
    price: 809,
    stock: 13,
    description: "¿Cuánto podrás sobrevivir en un mundo posapocalíptico?",
    category: "Shooter",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/221100/header.jpg?t=1674143992",
  },
  {
    id: 8,
    title: "GUILTY GEAR -STRIVE-",
    price: 799,
    stock: 15,
    description:
      "Vive la emoción de la batalla con las minuciosas mecánicas y las magníficas animaciones de Guilty Gear",
    category: "Lucha",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1384160/header.jpg?t=1685004154",
  },
];
